mapapp/urls.py
from django.urls import path, re_path
from django.views.generic import RedirectView

from . import api
from . import views

app_name = 'mapapp'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('pkmnadmin/', views.admin_page, name='admin'),
    path('login/', views.login_page, name='login'),
    path('signup/', views.signup_page, name='signup'),
    path('logout/', views.logout_page, name='logout'),
    path('pokedex/', views.pokedex_page, name='pokedex'),

    path('api/check_pkmn/', api.check_pkmn, name='check_pkmn'),
    path('api/get_user_pkmn/', api.get_user_pkmn, 
    name='get_user_pkmn'),
    path('api/capture_pkmn/', api.capture_pkmn, name='capture_pkmn'),
    path('api/add_pkmn/', api.add_pkmn, name='add_pkmn'),
    path('api/remove_pkmn/', api.remove_pkmn, name='remove_pkmn'),
    path('api/get_all_pkmn/', api.get_all_pkmn, name='get_all_pkmn'),
    path('api/shuffle_pkmn/', api.shuffle_pkmn, name='shuffle_pkmn'),
]

pokyomongo/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mapapp.urls', namespace='mapapp')),
]

mapapp/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models import Sum
import pokepy

class user_pkmn(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pkmn_id = models.IntegerField()
    state = models.IntegerField(default=0)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username + ' - ' + str(self.pkmn_id)
    
    def get_pkmn(self):
        client = pokepy.V2Client()
        return client.get_pokemon(self.pkmn_id)
    
class pkmn_locations(models.Model):
    pkmn_id = models.IntegerField()
    lat = models.FloatField()
    lon = models.FloatField()

    def __str__(self):
        return str(self.pkmn_id) + ' - ' + str(self.lat) + ' - ' + str(self.lon)
    
    def get_pkmn(self):
        client = pokepy.V2Client()
        return client.get_pokemon(self.pkmn_id)
    

mapapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from .models import user_pkmn
import pokepy

client = pokepy.V2Client()

# Create your views here.
def home_page(request):
    if request.user.is_authenticated:
        return render(request, 'index.html')
    else:
        return redirect('mapapp:login')

def admin_page(request):
    if request.user.is_authenticated and request.user.is_superuser:
        return render(request, 'admin.html')
    else:
        return redirect('mapapp:home')
    
def pokedex_page(request):
    if request.user.is_authenticated:
        dex = client.get_pokedex(1)[0].pokemon_entries
        pkmn_list = []
        user_pkmns = user_pkmn.objects.filter(user=request.user)

        for pkmn in dex:

            temp = {
                'id': pkmn.entry_number,
                'name': pkmn.pokemon_species.name,
                'captured': 0,
                'count': 0,
                'img': '',
            }

            if user_pkmns.filter(pkmn_id=pkmn.entry_number).exists():
                pkmn_img = client.get_pokemon(pkmn.entry_number)[0].sprites.front_default

                if user_pkmns.filter(pkmn_id=pkmn.entry_number).first().state == 1:
                    temp['captured'] = 2
                    temp['count'] = user_pkmns.filter(pkmn_id=pkmn.entry_number)[0].count
                else:
                    temp['captured'] = 1

                temp['img'] = pkmn_img

            pkmn_list.append(temp)

        return render(request, 'pokedex.html', {'pkmn_list': pkmn_list})
    else:
        return redirect('mapapp:login')

def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('mapapp:home')  
        
        else:
            error_message = "Invalid username or password."
    else:
        error_message = ""

    return render(request
    , 'login.html', {'error_message': error_message})

def signup_page(request):
    
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('mapapp:home')  
    else:
        form = UserCreationForm()

    return render(request, 'signup.html', {'form': form})

def logout_page(request):
    logout(request)
    return redirect('mapapp:login')

templates/admin.html
{% extends "base.html" %}

{% load static %}

{% block title %} Admin {% endblock %}

{% block content %}

<div class="container">
    <!--Title Section-->
    <div class="row ">
        <div class="col-md-12">
            <h1>Admin</h1>     
        </div>
    </div>

    <!--Map-->
    <div class="row mt-5">
        <div class="col-md-12">
            <h2>Map</h2>
            <div id="map"></div>
        </div>
    </div>


    <!--List-->
    <div class="row mt-5">
        <div class="col-md-12">
            <h2>Current List of Pokemon</h2>
            <div class="pokemon-wrapper">
                <table id="pokelist">
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Latitude</th>
                        <th>Longitude</th>
                        <th>Roll</th>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    
    <!--Form-->
    <div class="row mt-5">
        <div class="col-md-12">
            <h2>Shuffle</h2>
            <form id="shuffle-form" method="post">
                {% csrf_token %}
                <label for="number">Number of Pokemon:</label>
                <input type="number" id="number" name="number" required><br><br>
                
                <label for="selection">Shuffle Type:</label>
                <select id="shuffle-type" name="shuffle-type">
                    <option value="full">All</option>
                    <option value="partial">Locations Only</option>
                </select><br><br>
                
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>

</div>

{% endblock %}

{% block scripts %}
<script>
    var map = L.map('map');
    var markers = L.layerGroup().addTo(map);

    $(document).ready(function() {
        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 19,
            minZoom: 12,
            attribution: '© OpenStreetMap'
        }).addTo(map);

        map.setMaxBounds(MAP_BOUNDS);

        map.setView(MAP_BOUNDS.getCenter(), 12);

        function renderPkmnList() {
            $.get("{% url "mapapp:get_all_pkmn" %}", function(data){
                $('.poke-entry').remove();

                for (var i = 0; i < data.length; i++) {
                    let pkmn = data[i];
                    let listItem = `
                        <tr class="poke-entry">
                            <td class="p-3">${pkmn.id}</td>
                            <td class="p-3">${pkmn.name}</td>
                            <td class="p-3">${pkmn.lat}</td>
                            <td class="p-3">${pkmn.lon}</td>
                            <td class="p-3">${pkmn.capture_roll}</td>
                        </tr>
                    `;  

                    $('#pokelist').append(listItem);

                    let marker = L.marker([pkmn.lat, pkmn.lon]).addTo(map);
                    marker.bindPopup(`<b>${pkmn.name}</b><br>Roll: ${pkmn.capture_roll}`);
                }
            });
        }

        renderPkmnList();

        $('#shuffle-form').on('submit', function(e){
            e.preventDefault();
            var number = $('#number').val();
            var shuffleType = $('#shuffle-type').val();

            $.post("{% url "mapapp:shuffle_pkmn" %}", {
                number: number,
                shuffleType: shuffleType,
            }, function(data){
                renderPkmnList();
                clearSessionCaptured();
            });
        });

        
    });
</script>


{% endblock %}

templates/base.html
{% load static %}
<html lang="en-US">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>Pokyomon GO! | {% block title %}{% endblock %} </title>

        <!--Bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

        <!--Custom CSS-->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <!--JQuery and Leaflet-->
        <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
        crossorigin=""/>
        <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>


    </head>

    {% include "nav.html" %}
    
    <body>   
        {% if messages %}
        {% for message in messages %}
            <div class="dbMessage">{{ message }}</div>
        {% endfor %}
        {% endif %}

        <main class="container mt-5 pt-3">
            {% block content %}
            {% endblock %}
        </main>
        
        <!--Custom JS-->
        <script src="{% static 'js/scripts.js' %}"></script>

        <!--Inline JS-->
        {% block scripts %}
        {% endblock %}
    </body>
</html>

templates/index.html
{% extends "base.html" %}

{% load static %}

{% block title %} Explore Bishkek! {% endblock %}

{% block content %}

<div class="container">
    <!--Title Section-->
    <div class="row">
        <div class="col-md-12">
            <h1>Explore Bishkek</h1>

            <p>
                Start your very own pokemon adventure in Bishkek!
            </p>
        </div>
    </div>

    <!--Map Block-->

    <div class="row mt-5">
        <div class="col-md-12">
            <div id="map">
            </div>
        </div>
    </div>


    <!--Message Block-->
    <div class="row mt-5 mb-5">
        <div class="pkmn-border col-md-12 p-3">
            <div class="border-pkball tl">
                <img src="{% static "img/pokeball_icon.png" %}" alt="Pokeball">
            </div>
            <div class="border-pkball tr">
                <img src="{% static "img/pokeball_icon.png" %}" alt="Pokeball">
            </div>
            <p id="pkmn-message">
                No messages to show yet.
            </p>

            
            <div class="border-pkball bl">
                <img src="{% static "img/pokeball_icon.png" %}" alt="Pokeball">
            </div>
            <div class="border-pkball br">
                <img src="{% static "img/pokeball_icon.png" %}" alt="Pokeball">
            </div>
        </div>
    </div>
</div>

<!--Pokemon Modal-->


{% include "modal.html" %}

{% endblock %}


{% block scripts %}
<script>
    var map = L.map('map');
    var markers = L.layerGroup().addTo(map);
    var pkmn_to_marker = {};
    var captured = getSessionCaptured();
    const texts = [
        "while you explore Bishkek",
        "as you wander around Bishkek",
        "amidst your Bishkek adventures",
        "in the midst of your exploration of Bishkek",
        "while you discover the beauty of Bishkek",
        "as you roam the streets of Bishkek",
        "during your exploration of Bishkek",
        "in the process of getting to know Bishkek",
        "while you soak in the charm of Bishkek",
        "during your exploration of Bishkek",
        "as you explore Bishkek",
        "amidst your exploration of Bishkek",
        "in the process of exploring Bishkek",
        "while you discover Bishkek",
        "during your Bishkek exploration",
        "in the midst of exploring Bishkek",
        "while you get to know Bishkek",
        "during your investigation of Bishkek"
    ];

    const svgIcon = L.divIcon({
        html: `<img src="{% static "img/pokemarker.svg" %}">`,
        className: "",
        iconSize: [120, 200],
    });


    $(document).ready(function () {
        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 19,
            minZoom: 12,
            attribution: '© OpenStreetMap'
        }).addTo(map);

        map.setMaxBounds(MAP_BOUNDS);

        map.setView(MAP_BOUNDS.getCenter(), 12);

        function onMapClick(e) {
            // Get lat long of click event
            var lat = e.latlng.lat;
            var lng = e.latlng.lng;

            // Ajax call to get pokemon
            checkPkmn(L.latLng(lat, lng), function (data) {

                // Clear existing pkmn markers
                markers.clearLayers();

                markers = L.layerGroup().addTo(map);

                cap_count = 0

                // Ping circle
                var circle_opacity = 0.7;

                var circle = L.circle([lat, lng], 50, {
                    color: '#6A47B8',
                    fillColor: '#475CB8',
                    opacity: circle_opacity,
                    fillOpacity: circle_opacity
                }).addTo(map);

                var circlePoller = setInterval(function () {
                    circle.setRadius(circle.getRadius() + 50);
                    circle_opacity -= 0.025;
                    circle.setStyle({
                        opacity: circle_opacity,
                        fillOpacity: circle_opacity
                    });
                    if (circle.getRadius() > 2000) {
                        clearInterval(circlePoller);
                        map.removeLayer(circle);
                    }
                }, 25);

                // Add new pokemon markers
                for (var i = 0; i < data.length; i++) {
                    // Skip if pokemon is already captured in this particular session
                    if (captured.includes(data[i].id)) {
                        cap_count++;
                        continue;
                    }

                    var pkmn = data[i];
                    var pkmn_marker = L.marker([pkmn.lat, pkmn.lon], {
                        icon: svgIcon,
                        width: 24,
                        height: 40
                    })

                    pkmn_to_marker[pkmn.id] = pkmn_marker;

                    var popup_content = `
                        <div>
                            <div class="pkmn-id text-center">#${pkmn.id}</div>
                            <div class="pkmn-name text-center"><b>${pkmn.name}</b></div>
                            <div class="text-center"><img src="${pkmn.img}"></div>
                            <div class="text-center">
                            <button type="button" class="btn btn-primary capture-btn" data-toggle="modal" data-target="#pkmn-modal" data-id="${pkmn.id}">
                                View & Capture    
                            </button>
                            </div>
                        </div>
                    `;

                    pkmn_marker.bindPopup(popup_content).openPopup();
                    markers.addLayer(pkmn_marker);
                }

                // Update message section with randomized text and number of pkmn found
                var random_text = texts[Math.floor(Math.random() * texts.length)];

                $('#pkmn-message').text("You found " + (data.length - cap_count) + " pokemon" + " " +
                    random_text + '!');
            });
        }

        map.on('click', onMapClick);


        // Capture button handler
        $('body').on('click', '.capture-btn', function (e) {
            e.preventDefault();
            var pkmn_id = $(this).data('id');

            $.get("https://pokeapi.co/api/v2/pokemon/" + pkmn_id, function (data) {
                // Update modal with pokemon details
                $('#pkmn-modal .modal-pkmn-name').html(data.name);

                $('#pkmn-modal .modal-sprite').attr('src', data.sprites.front_default);

                $('#pkmn-modal .run-btn').show();
                $('#pkmn-modal .roll-btn').show();
                $('#pkmn-modal .leave-btn').hide();

                $('#pkmn-modal .roll-btn').attr('data-id', pkmn_id);
                $('#pkmn-modal .run-btn').attr('data-id', pkmn_id);

                $('#pkmn-modal .roll-message').html("Roll a d20 to capture " + data.name + "!");

                $('#pkmn-modal').modal('show');
            });
        }); 

        // Run button handler
        $('body').on('click', '.run-btn', function () {
            var pkmn_id = $('#pkmn-modal .run-btn').attr('data-id');

            // Remove marker from map
            //marker_to_remove = pkmn_to_marker[pkmn_id]._leaflet_id;
            //markers.removeLayer(marker_to_remove);

            
            // Clear existing pkmn markers
            markers.clearLayers();

            // Update message
            $('#pkmn-message').text("You ran away!");
            $('#pkmn-modal').modal('hide');
        });

        // Diceroll handler
        $('body').on('click', '.roll-btn', function () {
            var pkmn_id = $('#pkmn-modal .roll-btn').attr('data-id');

            // Temporarily disable pointer events
            $('body').css('pointer-events', 'none')

            //Dice animation
            var dice_poller = setInterval(function () {
                var dice = Math.floor(Math.random() * 20) + 1;
                $('#pkmn-modal .dice-number').html(dice);
            }, 100);

            // Hide buttons while rolling
            $('#pkmn-modal .run-btn').hide();
            $('#pkmn-modal .roll-btn').hide();

            $.get("{% url "mapapp:capture_pkmn" %}", {
                    pkmn_id: pkmn_id
                },
                function (data) {

                    pkmn_details = data.pkmn_info;

                    setTimeout(function () {
                        clearInterval(dice_poller);
                        
                        $('body').css('pointer-events', 'all')
                        $('#pkmn-modal .dice-number').html(data.roll + data.roll_bonus);

                        // Post diceroll
                        // Remove marker from map
                        //marker_to_remove = pkmn_to_marker[pkmn_id]._leaflet_id;

                        //markers.removeLayer(marker_to_remove);
                        
                        // Clear existing pkmn markers
                        markers.clearLayers();

                        // Add pokemon to captured list
                        captured.push(pkmn_id);
                        sessionStorage.setItem('captured', JSON.stringify(captured));

                        // Update message section
                        if (data.success) {
                            if (data.roll==20) {
                                $('#pkmn-modal .dice-number').html(20);

                                $('#pkmn-message').html("You captured <span class='pkmn-name'>" + pkmn_details.name + "</span> with a critical success!");

                                $('#pkmn-modal .roll-message').html("You captured <span class='pkmn-name'>" + pkmn_details.name + "</span> with a critical success!");
                            } else {
                                $('#pkmn-message').html("You captured <span class='pkmn-name'>" + pkmn_details.name + "</span> with a roll of " + (data.roll + data.roll_bonus) +"! " + data.roll_requirement + " required.");

                                $('#pkmn-modal .roll-message').html("You captured <span class='pkmn-name'>" + pkmn_details.name + "</span> with a roll of " + (data.roll + data.roll_bonus) +"! " + data.roll_requirement + " required.");
                            }
                        } else {
                            if (data.roll == 1) {
                                $('#pkmn-modal .dice-number').html(1);

                                $('#pkmn-message').html("You failed to capture <span class='pkmn-name'>" + pkmn_details.name + "</span> with a critical failure!");

                                $('#pkmn-modal .roll-message').html("You failed to capture <span class='pkmn-name'>" + pkmn_details.name + "</span> with a critical failure!");
                            } else {
                                $('#pkmn-message').html("You failed to capture <span class='pkmn-name'>" + pkmn_details.name + "</span> with a roll of " + (data.roll + data.roll_bonus) + "! " + data.roll_requirement + " required. Wild " + pkmn_details.name + " ran away!");

                                $('#pkmn-modal .roll-message').html("You failed to capture <span class='pkmn-name'>" + pkmn_details.name + "</span> with a roll of " + (data.roll + data.roll_bonus) + "! " + data.roll_requirement + " required. Wild " + pkmn_details.name + " ran away!");
                            }
                        }


                        // Show leave button after user is presented with result
                        $('#pkmn-modal .leave-btn').show();
                    }, 3000);
                });
        });

        // Leave button handler
        $('body').on('click', '.leave-btn', function () {
            $('#pkmn-modal').modal('hide');
        });



        // Given lat long, make ajax call and return a list of pokemon and their positions
        function checkPkmn(latlng, callback) {
            let lat = latlng.lat;
            let lng = latlng.lng;

            $.get("{% url "mapapp:check_pkmn" %}", {
                    lat: lat,
                    lng: lng
                },
                function (data) {
                    callback(data);
                });
        }

    });
</script>
{% endblock %}
```

templates/login.html
{% extends "base.html" %}

{% load static %}

{% block title %} Login and continue your Journey! {% endblock %}

{% block content %}

<!--Login form-->
<h2>Login</h2>

{% if error_message %}
    <p>{{ error_message }}</p>
{% endif %}

<form method="post">
    {% csrf_token %}
    <label for="username">Username:</label><br>
    <input type="text" id="username" name="username"><br>
    <label for="password">Password:</label><br>
    <input type="password" id="password" name="password"><br><br>
    <input type="submit" value="Login">

    <p>Don't have an account? <a href="{% url 'mapapp:signup' %}">Signup here</a></p>
</form>


{% endblock %}

templates/modal.html
<div class="modal fade" id="pkmn-modal" tabindex="-1" role="dialog" aria-labelledby="pkmnModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="pkmnModalLabel">Wild <span class="modal-pkmn-name"></span> Appeared!</h5>
        </div>
        <div class="modal-body text-center">
          <img src="" alt="" class="modal-sprite">

          <div class="dice-wrapper m-auto mt-3 mb-3">
            <div class="dice-inner">
                <div class="dice-number">20</div>
            </div>
          </div>

          <div class="roll-message">
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary run-btn" data-dismiss="modal" data-id="">Run Away</button>
          <button type="button" class="btn btn-primary roll-btn" data-id="">Roll to Catch!</button>
          <button type="button" class="btn btn-primary leave-btn">Leave</button>
        </div>
      </div>
    </div>
  </div>

templates/nav.html
<!--Navbar-->

<header class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        {% if user.is_authenticated %}
            <div class="user-info ms-3 me-3">
                Welcome, {{ user.username }}!
            </div>
        {% endif%}
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url "mapapp:home" %}" class="login-btn">Map</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url "mapapp:pokedex" %}" class="login-btn">Pokedex</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url "mapapp:logout" %}" class="login-btn">Logout</a></li>
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url "mapapp:login" %}" class="login-btn">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url "mapapp:signup" %}" class="login-btn">Signup</a></li>
            {% endif %}
    
            {% if user.is_superuser %}
                <li class="mobo-nav"><a class="nav-link" href="{% url "mapapp:admin" %}" class="login-btn">Admin</a></li>
            {% endif %}
        </ul>
    
    </nav>
    
</header>

templates/pokedex.html
{% extends "base.html" %}

{% load static %}

{% block title %} Your Pokedex! {% endblock %}

{% block content %}

<div class="container">
    <!--Title Section-->
    <div class="row">
        <div class="col-md-12">
            <h1>Your Pokedex!</h1>     
            
            <p>
                These are the pokemon that you have seen and caught! 
            </p>
        </div>
    </div>

    <div class="row mt-3">
        <div class="dex-controls mb-3">
            <button class="btn btn-primary" id="all-btn">All</button>
            <button class="btn btn-primary" id="seen-btn">Seen</button>
            <button class="btn btn-primary" id="caught-btn">Caught</button>
        </div>
        <div class="col-md-12 dex-results container row">
            {% for pkmn in pkmn_list %}
                <div class="col-md-3 dex-card" data-state="{{ pkmn.captured }}">
                    <div class="dex-card-inner card m-2 p-3">
                        <div class="dex-card-header text-center">
                            <h3>#{{ pkmn.id }} - {{ pkmn.name }}</h3>
                        </div>
                        <div class="dex-card-body text-center">
                            {% if pkmn.captured > 0 %}
                                <img width="100" height="100" src="{{ pkmn.img }}" alt="{{ pkmn.name }}">
    
                                {% if pkmn.captured > 1 %}
                                    <p>
                                        You have caught this pokemon {{ pkmn.count }} times!
                                    </p>
                                {% else %}
                                    <p>
                                        You have seen this pokemon!
                                    </p>
                                {% endif %}
    
                            {% else %}
                                <img width="100" height="100" src="{% static "img/questionmark.png" %}" alt="Uncaught Pokemon">
                                
                                <p>
                                    You have not seen this pokemon yet!
                                </p>
                            {% endif %}
                        </div>

                    </div>
                    
                </div>

            {% endfor %}

        </div>
    </div>
    

</div>

{% endblock %}


{% block scripts %}
<script>
    $(document).ready(function(){
        $('body').on('click', '#all-btn', function(){
            $('.dex-card').show()
        })

        $('body').on('click', '#seen-btn', function(){
            $('.dex-card').hide()
            $('.dex-card[data-state="1"]').show()
            $('.dex-card[data-state="2"]').show()
        })

        $('body').on('click', '#caught-btn', function(){
            $('.dex-card').hide()
            $('.dex-card[data-state="2"]').show()
        })
    })
</script>

{% endblock %}
```

templates/signup.html
{% extends "base.html" %}

{% load static %}

{% block title %} Signup and begin your Journey! {% endblock %}

{% block content %}
<div class="container">
    <h2>Sign Up</h2>

    <!--Signup form-->
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Sign Up">
    </form>
    <p>Already have an account? <a href="{% url 'mapapp:login' %}">Login</a></p>
</div>

{% endblock %}